### ISSUE TITLE
Allow piping credentials into login command

### ISSUE THREAD

**Issue by schrockwell** [usetrmnl/trmnlp#30]
`cat $TRMNL_API_KEY > trmnl login`

To help CI/CD deploy actions, e.g. #31

**Comment by andi4000** [comment]
hey, I submitted PR #56 for this, please check it out and tell me what you think. The approach with env var is AFAIK more common ([Ref](https://12factor.net/)). So the GH Action could look like this:

```yml
# Add API key to environment secrets, then:
steps:
  - name: Release Plugin
    env:
      TRMNL_API_KEY: ${{ secrets.TRMNL_API_KEY }}
    run: |
      trmnlp login
      trmnlp push
```
