### ISSUE TITLE
Create official GitHub action for deployment

### ISSUE THREAD

**Issue by schrockwell** [usetrmnl/trmnlp#31]
@Omeryl's idea

**Comment by stephenyeargin** [comment]
I built this one out to take care of my use case: https://github.com/stephenyeargin/trmnl-nfd-incidents/blob/main/.github/workflows/build.yml

Ran [into](https://github.com/stephenyeargin/trmnl-nfd-incidents/actions/runs/15647611707/job/44087603562#step:5:6) [some](https://github.com/stephenyeargin/trmnl-nfd-incidents/actions/runs/15647723837/job/44087869593) [headaches](https://github.com/stephenyeargin/trmnl-nfd-incidents/actions/runs/15647849697/job/44088195204) with dependencies until I finally just used Bundler. 🧘

**Comment by andi4000** [comment]
This simple GH workflow seems to work nicely:
```yml
jobs:
  setup-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Should read .ruby-version file, currently v3.4.1
      - uses: ruby/setup-ruby@v1

      - name: Install trmnlp from gem
        run: gem install trmnl_preview

      - name: Print trmnlp version
        run: trmnlp version

```
Job execution: https://github.com/andi4000/trmnl-open-meteo-weather-forecast/actions/runs/16090884604/job/45407642297
