### ISSUE TITLE
Cannot override polling_url in .trmnlp.yml

### ISSUE THREAD

**Issue by heroheman** [usetrmnl/trmnlp#47]
When i set a polling url in trmnlp.yml, it will be ignored as it will always poll from the default polling_url.
eg:
```
# override variables
variables:
  trmnl:
    plugin_settings:
      polling_url: https://example.com/api
```

It this is intended, the readme should be updated.
